Repository AY2122S2-CS2113-T11-4/tp, pull requests merged in 2022-03, with the labels that each got.

#15 Add input functionality.
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/controllers/Controller.java
  src/main/java/seedu/duke/controllers/MainController.java
  src/test/java/seedu/duke/DukeTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Chore

#20 Dish, Dish Manager, Dish Controller and JUnit test
  docs/AboutUs.md
  src/main/java/seedu/duke/controllers/DishController.java
  src/main/java/seedu/duke/entities/Dish.java
  src/main/java/seedu/duke/manager/DishManager.java
  src/test/java/seedu/duke/entities/DishTest.java
  src/test/java/seedu/duke/manager/DishManagerTest.java
Labels: type.Story, priority.High

#29 Add class for getting input from user.
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/controllers/Controller.java
  src/main/java/seedu/duke/controllers/InputParser.java
  src/main/java/seedu/duke/controllers/MainController.java
  src/main/java/seedu/duke/exceptions/OperationTerminationException.java
  src/test/java/seedu/duke/controllers/ControllerTest.java
Labels: priority.High, type.Chore

#32 Display Receipt for confirmed orders
  src/main/java/seedu/duke/controllers/OrderController.java
  src/main/java/seedu/duke/manager/DishManager.java
  src/main/java/seedu/duke/manager/OrderManager.java
Labels: priority.High, type.Epic

#35 Staff: change exception handling and input parsing
  src/main/java/seedu/duke/controllers/InputParser.java
  src/main/java/seedu/duke/controllers/StaffController.java
  src/main/java/seedu/duke/entities/Staff.java
  src/main/java/seedu/duke/manager/StaffManager.java
Labels: priority.High, type.Chore

#36 Reformat order controllers
  src/main/java/seedu/duke/controllers/OrderController.java
  src/test/java/seedu/duke/entities/OrderTest.java
Labels: severity.High

#42 Allow entering other Controllers and fix formatting for StaffController
  src/main/java/seedu/duke/controllers/DishController.java
  src/main/java/seedu/duke/controllers/InputParser.java
  src/main/java/seedu/duke/controllers/MainController.java
  src/main/java/seedu/duke/controllers/OrderController.java
  src/main/java/seedu/duke/controllers/StaffController.java
  src/main/java/seedu/duke/entities/Dish.java
  src/main/java/seedu/duke/entities/Order.java
  src/main/java/seedu/duke/entities/Staff.java
  src/main/java/seedu/duke/manager/DishManager.java
  src/main/java/seedu/duke/manager/OrderManager.java
  src/main/java/seedu/duke/manager/StaffManager.java
  src/test/java/seedu/duke/entities/OrderTest.java
  src/test/java/seedu/duke/entities/StaffTest.java
  src/test/java/seedu/duke/manager/DishManagerTest.java
Labels: priority.High, type.Chore

#48 Add test for InputParser and add some logging for MainController.
  src/main/java/seedu/duke/controllers/DishController.java
  src/main/java/seedu/duke/controllers/InputParser.java
  src/main/java/seedu/duke/controllers/MainController.java
  src/main/java/seedu/duke/controllers/OrderController.java
  src/main/java/seedu/duke/controllers/StaffController.java
  src/test/java/seedu/duke/controllers/ControllerTest.java
  src/test/java/seedu/duke/controllers/InputParserTest.java
Labels: priority.High, type.Chore

#59 Add abstract Manager class for dealing with database.
  src/main/java/seedu/duke/manager/Manager.java
Labels: priority.High

#68 Fix Manager implementation
  src/main/java/seedu/duke/controllers/DishController.java
  src/main/java/seedu/duke/manager/DishManager.java
  src/main/java/seedu/duke/manager/DishStorageManager.java
  src/test/java/seedu/duke/manager/StaffManagerTest.java
Labels: severity.High

#72 Do not make logger log to console.
  classes/artifacts/tp_jar/tp.jar
  src/main/java/seedu/duke/loggers/MainLogger.java
Labels: severity.Mid

#76 Database for staff
  src/main/java/seedu/duke/controllers/StaffController.java
  src/main/java/seedu/duke/entities/Staff.java
  src/main/java/seedu/duke/manager/StaffManager.java
Labels: priority.High

#77 Add DG for Controllers and Managers and basic overview
  docs/DeveloperGuide.md
  docs/UML/all.puml
  docs/UML/controller.puml
  docs/UML/manager.puml
  docs/diagrams/class/all.png
  docs/diagrams/class/controller.png
  docs/diagrams/class/manager.png
Labels: priority.High

#87 Format doc folder
  docs/uml/class/all.puml
  docs/uml/class/controller.puml
  docs/uml/class/manager.puml
  docs/uml/sequence/DishManager_addDish.puml
  docs/uml/sequence/DishManager_deleteDish.puml
  docs/uml/sequence/DishManager_printDishes.puml
Labels: priority.Low

#89 make ordermanager work
  docs/AboutUs.md
  src/main/java/seedu/duke/controllers/DishController.java
  src/main/java/seedu/duke/controllers/OrderController.java
  src/main/java/seedu/duke/entities/Order.java
  src/main/java/seedu/duke/manager/OrderManager.java
Labels: priority.High

#88 Staff dg 1
  docs/uml/sequence/StaffManager_addStaff.puml
  docs/uml/sequence/StaffManager_deleteStaff.puml
  src/main/java/seedu/duke/controllers/StaffController.java
  src/main/java/seedu/duke/entities/Dish.java
  src/main/java/seedu/duke/entities/Staff.java
  src/main/java/seedu/duke/manager/StaffManager.java
Labels: priority.High

#97 Junit staff
  src/main/java/seedu/duke/entities/Dish.java
  src/main/java/seedu/duke/entities/Staff.java
  src/test/java/seedu/duke/entities/DishTest.java
  src/test/java/seedu/duke/entities/OrderTest.java
  src/test/java/seedu/duke/manager/DishManagerTest.java
  src/test/java/seedu/duke/manager/StaffManagerTest.java
Labels: priority.Medium

#98 Fix small bug and add UG
  docs/UserGuide.md
  src/main/java/seedu/duke/manager/DishManager.java
Labels: priority.High
